# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51483e7756433935c7e3b70da06f4f283a90b1d12e5b079e86011c71509373d95697444c072c7f1ce70f48e3707477620f9d60d6dff464ecb3e8c077ac39bd52

test:
  secret_key_base: ec46d005dc2555a2ff9334dd43f42c7fe077e5ccb1eda9e373b8610a0a66b371eaf2dc137268d7fa260621643c48ba945961dc2c6c03a36d7fd9987055d1a9d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
